# task list
- ProgramSamplerConfig:
    input_path: "input.txt"
    sample_config:
      num_snippets: [1, 2] # int or list[int]
      data_size: 20
      spec_num: 5
      max_spec_size: 30
      save_correct_program: true
      program_prefix: "string_manipulation" # add suffix if num_snippets is list
      program_dir: "programs" 
      prompt_dir: "prompts"
      seed: 114514 # add prefix if num_snippets is list

  SynthesizerConfig:

    - name: "gpt"
      model_name: "gpt-3.5-turbo-0301"
      synthesizer_class:
        name: "GPTSynthesizer"
      prompt_wrapper_class:
        name: "GPTPromptWrapper"
      response_wrapper_class:
        name: "GPTResponseWrapper"

    - name: "anpl"
      model_name: "gpt-3.5-turbo-0301"
      synthesizer_class:
        name: "ANPLSynthesizer"
        args: # only support kerword args now
          max_try_times: 5
          max_temperature: 0.5
      prompt_wrapper_class:
        name: "ANPLPromptWrapper"
      response_wrapper_class:
        name: "ANPLResponseWrapper"

    - name: "parsel"
      model_name: "gpt-3.5-turbo-0301"
      synthesizer_class:
        name: "ParselSynthesizer"
      prompt_wrapper_class:
        name: "ParselPromptWrapper"
      response_wrapper_class:
        name: "ParselResponseWrapper"

